# Generated by Django 2.1.7 on 2019-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_cbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='status',
            field=models.CharField(default='Inactive', max_length=10),
        ),
    ]
